version: '3.8'
services:
  product-database:
    image: mongo:latest
    container_name: product-database
    ports:
      - "27017:27017"
    volumes:
      - './mongo/data:/data/db'
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_interval: 5s

  inventory-database:
    image: mysql:latest
    container_name: inventory-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_PASSWORD: root
    ports:
      - "3316:3306"
    volumes:
      - './mysql/data:/var/lib/mysql'
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
      start_interval: 5s

  products:
    build:
      context: ./products/
    ports:
      - "8090:8090"
    depends_on:
      product-database:
        condition: service_healthy

  inventory:
    build:
      context: ./inventory
    ports:
      - "8092:8092"
    depends_on:
      inventory-database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://inventory-database:3306/inventory
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root