spring:
  application:
    name: products
  data:
    mongodb:
      host: localhost
      port: 27017
      database: products
      repositories:
        enabled: true
server:
  port: 8090

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"